### ISSUE TITLE
Frontend Auth (Signin, Signup, Splash, Customized Routes)

### ISSUE THREAD

**Issue by lindamckeithlam** [lindamckeithlam/Screamless#3]
## [New account creation] 03/28/19

- [x] User/Session is completely styled and seeded
- [x] User/Session is bug free with smooth navigation
- [x] User/Session is bug free on a hard refresh (⌘ + R)
- [x] User/Session handles errors with informative messages for user
_Use the space below for features specific to your app/MVP for review_
- [x] [Splash Page]
- [x] [External Links]
- [x] [Auth/Protected Routes]

**Comment by david-dickinson** [comment]
- [ ] Style errors to appear more inline with fields
- [ ] Repeat the error message functionality on sign up with sign in when blank fields are submitted
- [ ] Get rid of the `Get the app` link until it has specific functionality (for now, you can replace it with a specific `Sign Up` link, so it doesn't have unexpected functionality)
